name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .
      - name: CLI smoke
        run: skoolhud --help

      # Optional: Live-Run nur mit Secret
      - name: Daily update (optional)
        if: ${{ secrets.SKOOL_COOKIE != '' }}
        env:
          SKOOL_COOKIE: ${{ secrets.SKOOL_COOKIE }}
        run: |
          echo "$SKOOL_COOKIE" > cookie.txt
          skoolhud init-db
          skoolhud add-tenant --slug hoomans --group hoomans --cookie "$SKOOL_COOKIE"
          skoolhud test-tenant --slug hoomans
          python update_all.py
          python skoolhud/ai/agents/run_all_agents.py
