# REPLACE FILE: .github/workflows/daily.yml
name: Daily

on:
  schedule:
    - cron: "5 5 * * *"   # daily at 05:05 UTC (~07:05 Berlin)
  workflow_dispatch:

jobs:
  run-daily:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SKOOL_COOKIE: ${{ secrets.SKOOL_COOKIE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -e .

      - name: Run daily (guarded if SKOOL_COOKIE is present)
        run: |
          if [ -z "${SKOOL_COOKIE}" ]; then
            echo "SKOOL_COOKIE not set; skipping live run."
            exit 0
          fi
          echo "$SKOOL_COOKIE" > cookie.txt
          skoolhud init-db
          skoolhud add-tenant --slug hoomans --group hoomans --cookie "$(cat cookie.txt)"
          skoolhud test-tenant --slug hoomans
          python update_all.py
          python skoolhud/ai/agents/run_all_agents.py --slug hoomans
